package com.sm.nadaman.common.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.sm.nadaman.common.bean.Friend;
import com.sm.nadaman.common.bean.Health;
import com.sm.nadaman.common.bean.UserList;
import com.sm.nadaman.common.bean.Ecg12Data;

import com.sm.nadaman.common.dao.FriendDao;
import com.sm.nadaman.common.dao.HealthDao;
import com.sm.nadaman.common.dao.UserListDao;
import com.sm.nadaman.common.dao.Ecg12DataDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig friendDaoConfig;
    private final DaoConfig healthDaoConfig;
    private final DaoConfig userListDaoConfig;
    private final DaoConfig ecg12DataDaoConfig;

    private final FriendDao friendDao;
    private final HealthDao healthDao;
    private final UserListDao userListDao;
    private final Ecg12DataDao ecg12DataDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        friendDaoConfig = daoConfigMap.get(FriendDao.class).clone();
        friendDaoConfig.initIdentityScope(type);

        healthDaoConfig = daoConfigMap.get(HealthDao.class).clone();
        healthDaoConfig.initIdentityScope(type);

        userListDaoConfig = daoConfigMap.get(UserListDao.class).clone();
        userListDaoConfig.initIdentityScope(type);

        ecg12DataDaoConfig = daoConfigMap.get(Ecg12DataDao.class).clone();
        ecg12DataDaoConfig.initIdentityScope(type);

        friendDao = new FriendDao(friendDaoConfig, this);
        healthDao = new HealthDao(healthDaoConfig, this);
        userListDao = new UserListDao(userListDaoConfig, this);
        ecg12DataDao = new Ecg12DataDao(ecg12DataDaoConfig, this);

        registerDao(Friend.class, friendDao);
        registerDao(Health.class, healthDao);
        registerDao(UserList.class, userListDao);
        registerDao(Ecg12Data.class, ecg12DataDao);
    }
    
    public void clear() {
        friendDaoConfig.clearIdentityScope();
        healthDaoConfig.clearIdentityScope();
        userListDaoConfig.clearIdentityScope();
        ecg12DataDaoConfig.clearIdentityScope();
    }

    public FriendDao getFriendDao() {
        return friendDao;
    }

    public HealthDao getHealthDao() {
        return healthDao;
    }

    public UserListDao getUserListDao() {
        return userListDao;
    }

    public Ecg12DataDao getEcg12DataDao() {
        return ecg12DataDao;
    }

}
